### ISSUE TITLE
Error while polling coordinator

### ISSUE THREAD

**Issue by gbrlstr** [ThorConzales/Dota2SentinelBot#1]
I have this problem.
Could you tell me which part I'm missing?

LOG:

```
> 2017-07-18 16:12:20,930 INFO  [anonymousce] Dota2Client.DotaClient - Initiating Steam connection
> 2017-07-18 16:12:24,174 INFO  [anonymousce] Dota2Client.DotaClient - Connection successful - Logging in anonymousce
> 2017-07-18 16:12:29,020 INFO  [anonymousce] Dota2Client.DotaClient - Login successful - Launching Dota 2
> 2017-07-18 16:12:34,908 INFO  [anonymousce] Dota2Client.DotaClient - Client connection status
> 2017-07-18 16:12:35,081 INFO  [anonymousce] Dota2Client.DotaClient - Disconnected from Steam
> 2017-07-18 16:12:36,202 INFO  [anonymousce] Dota2Client.DotaClient - Initiating Steam connection
> 2017-07-18 16:12:37,122 INFO  [anonymousce] Dota2Client.DotaClient - Connection successful - Logging in anonymousce
> 2017-07-18 16:12:37,857 INFO  [anonymousce] Dota2Client.DotaClient - Login successful - Launching Dota 2
> 2017-07-18 16:12:43,691 INFO  [anonymousce] Dota2Client.DotaClient - Dota 2 launch successful - Client version: 2312
> 2017-07-18 16:12:43,710 INFO  [anonymousce] Dota2Client.DotaClient - Joining chat: Dota2SentinelAdmin
> 2017-07-18 16:12:43,717 INFO  [anonymousce] Dota2Client.DotaClient - Joining chat: 498108721
> 2017-07-18 16:12:43,730 INFO  [anonymousce] Dota2Client.DotaClient - Joining chat: OverthrowPrivateChannel
> 2017-07-18 16:12:44,635 INFO  [anonymousce] Dota2SentinelCoordinatorBot.CoordinatorBot - Joined channel - Name 498108721 ID: 500
> 2017-07-18 16:12:44,646 INFO  [anonymousce] Dota2SentinelCoordinatorBot.CoordinatorBot - Joined channel - Name OverthrowPrivateChannel ID: 3179211
> 2017-07-18 16:12:44,649 INFO  [anonymousce] Dota2SentinelCoordinatorBot.CoordinatorBot - Joined channel - Name Dota2SentinelAdmin ID: 3179212
> 2017-07-18 16:12:47,153 INFO  [DR34MH1GH] Dota2Client.DotaClient - Initiating Steam connection
> 2017-07-18 16:12:50,912 INFO  [DR34MH1GH] Dota2Client.DotaClient - Connection successful - Logging in DR34MH1GH
> 2017-07-18 16:12:54,186 INFO  [DR34MH1GH] Dota2Client.DotaClient - Login successful - Launching Dota 2
> 2017-07-18 16:13:00,895 INFO  [DR34MH1GH] Dota2Client.DotaClient - Client connection status
> 2017-07-18 16:13:00,935 INFO  [DR34MH1GH] Dota2Client.DotaClient - Unhandled message: 7388
> 2017-07-18 16:13:01,112 INFO  [DR34MH1GH] Dota2Client.DotaClient - Dota 2 launch successful - Client version: 2312
> 2017-07-18 16:13:01,171 INFO  [DR34MH1GH] Dota2Client.DotaClient - Leave current lobby
> 2017-07-18 16:13:04,952 ERROR [DR34MH1GH] Dota2Client.DotaClient - Error while polling coordinator tasks: An error occurred while sending the request.
> 2017-07-18 16:13:04,952 ERROR [DR34MH1GH] Dota2Client.DotaClient - Error while polling coordinator tasks: An error occurred while sending the request.
> 2017-07-18 16:13:04,952 ERROR [DR34MH1GH] Dota2Client.DotaClient - Error while polling coordinator tasks: An error occurred while sending the request.
> 2017-07-18 16:13:04,952 ERROR [DR34MH1GH] Dota2Client.DotaClient - Error while polling coordinator tasks: An error occurred while sending the request.
> 2017-07-18 16:13:05,365 ERROR [DR34MH1GH] Dota2Client.DotaClient - Error while polling coordinator tasks: An error occurred while sending the request.
> 2017-07-18 16:13:05,891 ERROR [DR34MH1GH] Dota2Client.DotaClient - Error while polling coordinator tasks: An error occurred while sending the request.
> 
```

**Comment by ErkoKnoll** [comment]
It is failing in https://github.com/ThorConzales/Dota2SentinelBot/blob/master/Dota2SentinelLobbyBot/Program.cs and the error message is printed out on line 95. For some reason it cannot poll the coordinator bot's queue. Worth checking is the port where the coordinator bot runs, it is configured to run on port 5000.

This exception that is being thrown is not informative at all but if you add a breakpoint on that line and look at the inner exception it should reveal the actual cause, but most likely it is related to connection issue. Either the hostname differs (which by default is localhost) or the port which by default is 5000.

In case the Kestrel's port (coordinator bot) is not 5000 or the hostname needs changing you can do that in config.json by looking for "coordinatorUrl" key.

Try hitting http://localhost:5000/api/coordinator/, if it works it should return some http error code (because you are not sending the proper format), but if the Kestrel failed to start up properly then this URL won't respond and you should get connection timed out.

**Comment by gbrlstr** [comment]
The server started at http: // localhost: 61186, port 5000 was off the web.
I modified the coordinatorUrl to coordinatorUrl port: 61186 and it worked.

I have a question is it possible to create game lobby x5 with cm or ap mode?

**Comment by ErkoKnoll** [comment]
If those modes can be specified while creating the lobby then yes, but as far as I remember the only thing you can select while creating a custom lobby is the map, and every other setting that is applied is applied by the host when the host has connected to the game server. As the bot is only communicating with the Game Coordinator then I'm afraid any in-game setting that needs to be applied afterwards is out of the bot's reach. 

At least with the current implementation. Theoretically it would be possible to make the bot also join the game and apply those settings as the host, but then remains the problem that the bot will waste 1 player slot, not to mention challenge of communicating with the game server which is far more challenging that communicating with Game Coordinator, because thanks to the guys who created SteamKit library GC communication is relatively easy.
